"""Plumbing for Lab 08: load the dataset, run Great Expectations suites, print a report, and publish or block.

You do not edit this file. The exercises are in exercises.py, and solutions.py has the reference answers.

The flow, for `--stage clean` (the default):

    raw files ──► clean (dedupe, normalise, drop invalid rows) ──► validate ──► gate ──► publish
                                                                                  │
                                                                                  └── a critical failure blocks publishing

`--stage raw` validates the files exactly as they arrived and publishes nothing: it shows what the
suites find in the source data.

The dataset folder can be changed with LAB_DATA_DIR (default: ../data/output).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable

import great_expectations as gx
import pandas as pd

LAB = Path(__file__).resolve().parent
DATA = Path(os.environ.get("LAB_DATA_DIR", LAB.parent / "data" / "output"))
OUT = LAB / "output"


@dataclass
class Reference:
    """Values from other tables, for checks that compare a table with its parents."""
    order_ids: list[int]
    product_ids: list[int]


@dataclass
class Outcome:
    """One expectation's result, reduced to what a reader or a gate needs."""
    dataset: str
    check: str
    column: str
    severity: str               # "critical", "warning" or "info"
    success: bool
    unexpected_count: int | None
    unexpected_percent: float | None
    observed: str | None


# ── Loading and cleaning ─────────────────────────────────────────────────────
def load_raw() -> dict[str, pd.DataFrame]:
    orders = pd.read_csv(DATA / "orders.csv")
    orders["order_ts"] = pd.to_datetime(orders["order_ts"], utc=True)
    events = pd.read_json(DATA / "events.jsonl", lines=True)
    for column in ("event_ts", "received_ts"):
        events[column] = pd.to_datetime(events[column], utc=True)
    return {
        "orders": orders,
        "order_items": pd.read_csv(DATA / "order_items.csv"),
        "events": events,
        "products": pd.read_csv(DATA / "products.csv"),
    }


def clean(raw: dict[str, pd.DataFrame]) -> tuple[dict[str, pd.DataFrame], dict[str, int]]:
    """The staging rules from Lab 06: latest version of each order, lowercase status, valid lines only."""
    orders = (raw["orders"].sort_values("updated_at").drop_duplicates("order_id", keep="last")
              .assign(status=lambda d: d["status"].str.lower()).sort_values("order_id"))
    items = raw["order_items"]
    valid = (items["quantity"] > 0) & items["product_id"].isin(raw["products"]["product_id"])
    events = raw["events"].drop_duplicates("event_id")
    rejected = {
        "duplicate order versions": len(raw["orders"]) - len(orders),
        "invalid order lines": int((~valid).sum()),
        "duplicate event deliveries": len(raw["events"]) - len(events),
    }
    return {"orders": orders, "order_items": items[valid], "events": events, "products": raw["products"]}, rejected


# ── Validation ───────────────────────────────────────────────────────────────
def validate(context, stage: str, dataset: str, df: pd.DataFrame, expectations: list) -> list[Outcome]:
    """Run a list of expectations against a DataFrame and return one Outcome per expectation."""
    name = f"{stage}_{dataset}"
    asset = context.data_sources.add_pandas(name).add_dataframe_asset(dataset)
    batch_definition = asset.add_batch_definition_whole_dataframe("whole")
    suite = context.suites.add(gx.ExpectationSuite(name=name))
    for expectation in expectations:
        suite.add_expectation(expectation)
    definition = context.validation_definitions.add(
        gx.ValidationDefinition(name=name, data=batch_definition, suite=suite))
    result = definition.run(batch_parameters={"dataframe": df}, result_format="SUMMARY")

    outcomes = []
    for r in result.results:
        config = r.expectation_config
        kwargs = config.kwargs
        column = kwargs.get("column") or ",".join(kwargs.get("column_list", [])) or kwargs.get("column_A", "")
        observed = r.result.get("observed_value")
        outcomes.append(Outcome(
            dataset=dataset,
            check=config.type.removeprefix("expect_"),
            column=column,
            severity=str(getattr(config.severity, "value", config.severity)),
            success=bool(r.success),
            unexpected_count=r.result.get("unexpected_count"),
            unexpected_percent=r.result.get("unexpected_percent"),
            observed=None if observed is None else str(observed),
        ))
    return outcomes


def print_report(dataset: str, rows: int, outcomes: list[Outcome]) -> None:
    print(f"\n{dataset} ({rows:,} rows)")
    for o in outcomes:
        detail = ""
        if o.unexpected_count is not None:
            detail = f"{o.unexpected_count:,} unexpected ({o.unexpected_percent:.2f}%)"
        elif o.observed is not None:
            detail = f"observed {o.observed[:60]}"
        label = f"{o.check}[{o.column}]" if o.column else o.check
        print(f"  {'PASS' if o.success else 'FAIL'}  {o.severity:<8}  {label:<62} {detail}")


# ── The run ──────────────────────────────────────────────────────────────────
def run(orders_expectations: Callable, items_expectations: Callable, events_expectations: Callable,
        gate: Callable[[list[Outcome]], list[Outcome]]) -> int:
    """Validate every table, apply the gate, and publish only if nothing blocks. Returns the exit code."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--stage", choices=["raw", "clean"], default="clean")
    args = parser.parse_args()

    raw = load_raw()
    if args.stage == "clean":
        tables, rejected = clean(raw)
        print("Cleaning removed: " + ", ".join(f"{n:,} {what}" for what, n in rejected.items()))
    else:
        tables = raw
        print("Validating the raw files as they arrived; nothing is cleaned or published.")

    reference = Reference(order_ids=[int(i) for i in tables["orders"]["order_id"].unique()],
                          product_ids=[int(i) for i in tables["products"]["product_id"]])
    suites = {"orders": orders_expectations, "order_items": items_expectations, "events": events_expectations}
    context = gx.get_context()                          # in memory: nothing is written to disk
    outcomes: list[Outcome] = []
    for dataset, build in suites.items():
        results = validate(context, args.stage, dataset, tables[dataset], build(reference))
        print_report(dataset, len(tables[dataset]), results)
        outcomes += results

    blocking = gate(outcomes)
    failed = [o for o in outcomes if not o.success]
    warnings = [o for o in failed if o not in blocking]
    print(f"\n{len(outcomes)} checks: {len(outcomes) - len(failed)} passed, {len(blocking)} blocking, "
          f"{len(warnings)} not blocking")

    OUT.mkdir(exist_ok=True)
    (OUT / "quality_report.json").write_text(json.dumps(
        {"stage": args.stage, "blocked": bool(blocking), "outcomes": [asdict(o) for o in outcomes]}, indent=2))

    if blocking:
        print("BLOCKED: " + "; ".join(f"{o.dataset}.{o.check}[{o.column}]" for o in blocking))
        print("Nothing was published. The previous published tables, if any, are unchanged.")
        return 1
    if args.stage == "clean":
        published = OUT / "published"
        published.mkdir(exist_ok=True)
        for dataset in suites:
            tables[dataset].to_csv(published / f"{dataset}.csv", index=False)
        print(f"PUBLISHED {len(suites)} tables to {published.relative_to(LAB)}/")
    return 0


def main(*args, **kwargs) -> None:
    sys.exit(run(*args, **kwargs))
