"""Plumbing for the applier: read change events from Kafka in batches, stage a batch in DuckDB, and commit.

You do not edit this file. The exercise is in applier.py (the reference answer is in solutions/applier.py).

The flow for each batch of Kafka messages:

    parse events ──► latest_per_key() ──► add_new_columns() ──► merge() into the target ──► commit the DuckDB transaction ──► commit the Kafka offsets

Offsets are committed only after the batch is safely in the target, so a crash means a batch is delivered
again (at-least-once). The apply must therefore be safe to repeat.
"""
from __future__ import annotations

import argparse
import json
import random
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import duckdb
from confluent_kafka import Consumer

from common import BOOTSTRAP, KEYS, TARGET_DB, TOPICS

# The columns of the source tables when the lab starts. Later columns are handled by add_new_columns().
COLUMNS = {
    "orders": ["order_id", "customer_id", "order_ts", "status", "currency", "updated_at"],
    "order_items": ["order_id", "line_no", "product_id", "quantity", "unit_price"],
}
TYPES = {"order_id": "BIGINT", "customer_id": "INTEGER", "order_ts": "TIMESTAMPTZ", "status": "VARCHAR",
         "currency": "VARCHAR", "updated_at": "TIMESTAMPTZ", "line_no": "INTEGER", "product_id": "INTEGER",
         "quantity": "INTEGER", "unit_price": "DECIMAL(10, 2)"}


@dataclass
class Change:
    """One change event, reduced to what the target needs."""
    table: str
    key: tuple
    lsn: int                    # position in the source's transaction log: orders the changes to a row
    op: str                     # r (snapshot read), c, u or d
    row: dict                   # the new row; for a delete, only the key columns

    @property
    def deleted(self) -> bool:
        return self.op == "d"


def parse(table: str, value: bytes | None) -> Change | None:
    """Turn a Kafka message value into a Change. Returns None for a tombstone (a message with no value)."""
    if value is None:
        return None
    event = json.loads(value)
    if event["op"] == "d":
        row = {k: event["before"][k] for k in KEYS[table]}      # a delete's `before` is trustworthy only for the key
    else:
        row = event["after"]
    return Change(table, tuple(row[k] for k in KEYS[table]), event["source"]["lsn"], event["op"], row)


def create_tables(con: duckdb.DuckDBPyConnection) -> None:
    for table, columns in COLUMNS.items():
        definitions = ", ".join(f"{c} {TYPES[c]}" for c in columns)
        con.execute(f"CREATE TABLE IF NOT EXISTS {table} ({definitions}, _lsn BIGINT, _deleted BOOLEAN DEFAULT false, "
                    f"PRIMARY KEY ({', '.join(KEYS[table])}))")


def columns_of(con: duckdb.DuckDBPyConnection, table: str) -> list[tuple[str, str]]:
    """The target table's business columns as (name, DuckDB type), without the _lsn and _deleted bookkeeping columns."""
    return [(name, type_) for name, type_ in con.execute(
        "SELECT column_name, data_type FROM information_schema.columns WHERE table_name = ? "
        "AND column_name NOT IN ('_lsn', '_deleted') ORDER BY ordinal_position", [table]).fetchall()]


def stage_batch(con: duckdb.DuckDBPyConnection, table: str, changes: list[Change]) -> None:
    """Load a batch into a temporary table `stage` with the target's columns plus _lsn and _deleted.

    Only the columns the target has are staged: a field the target does not know is dropped here.
    Rows are staged through a JSON file: a multi-row INSERT with thousands of bound parameters is far slower.
    """
    columns = columns_of(con, table)
    with tempfile.TemporaryDirectory() as folder:
        path = Path(folder) / "batch.jsonl"
        with open(path, "w", encoding="utf-8") as f:
            for c in changes:
                f.write(json.dumps({**{name: c.row.get(name) for name, _ in columns}, "_lsn": c.lsn, "_deleted": c.deleted}) + "\n")
        declared = ", ".join(f"'{name}': 'VARCHAR'" for name, _ in columns)
        casts = ", ".join(f"{name}::{type_} AS {name}" for name, type_ in columns)
        con.execute(f"CREATE OR REPLACE TEMP TABLE stage AS SELECT {casts}, _lsn, _deleted FROM read_json(?, "
                    f"format = 'newline_delimited', columns = {{{declared}, '_lsn': 'BIGINT', '_deleted': 'BOOLEAN'}})", [str(path)])


def run(latest_per_key: Callable[[list[Change]], list[Change]],
        merge: Callable[[duckdb.DuckDBPyConnection, str, list[Change]], None],
        add_new_columns: Callable[[duckdb.DuckDBPyConnection, str, list[Change]], None]) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--group", default="applier", help="consumer group; a new name starts from the beginning of the topics")
    parser.add_argument("--idle-seconds", type=float, default=8, help="stop after this long without messages")
    parser.add_argument("--max-messages", type=int, default=0, help="stop after this many messages (0 = no limit)")
    parser.add_argument("--chaos", choices=["duplicate", "shuffle", "reverse"],
                        help="duplicate: apply every batch twice; shuffle: random order within a batch; "
                             "reverse: apply the batches newest first")
    args = parser.parse_args()

    con = duckdb.connect(str(TARGET_DB))
    create_tables(con)
    consumer = Consumer({"bootstrap.servers": BOOTSTRAP, "group.id": args.group, "auto.offset.reset": "earliest",
                         "enable.auto.commit": False})
    consumer.subscribe(list(TOPICS.values()))
    table_of = {topic: table for table, topic in TOPICS.items()}
    rng, idle, read, tombstones, batches = random.Random(7), 0.0, 0, 0, []

    def apply(batch: list) -> None:
        nonlocal tombstones
        changes: dict[str, list[Change]] = {t: [] for t in COLUMNS}
        for message in batch:
            change = parse(table_of[message.topic()], message.value())
            if change is None:
                tombstones += 1
            else:
                changes[change.table].append(change)
        con.execute("BEGIN")
        for table, table_changes in changes.items():
            if args.chaos == "shuffle":
                rng.shuffle(table_changes)
            reduced = latest_per_key(table_changes)
            add_new_columns(con, table, reduced)
            merge(con, table, reduced)
            if args.chaos == "duplicate":
                merge(con, table, reduced)                       # the same batch, delivered again
        con.execute("COMMIT")

    while idle < args.idle_seconds and not (args.max_messages and read >= args.max_messages):
        batch = [m for m in consumer.consume(num_messages=500, timeout=1.0) if not m.error()]
        if not batch:
            idle += 1.0
            continue
        idle, read = 0.0, read + len(batch)
        if args.chaos == "reverse":
            batches.append(batch)                                # hold everything back, apply newest first below
            continue
        apply(batch)
        consumer.commit(asynchronous=False)                      # after the batch is applied: at-least-once
    for batch in reversed(batches):
        apply(batch)
    consumer.close()
    print(f"read {read:,} messages ({tombstones:,} tombstones)")
